package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CumRapAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCumRapAllPropertiesEquals(CumRap expected, CumRap actual) {
        assertCumRapAutoGeneratedPropertiesEquals(expected, actual);
        assertCumRapAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCumRapAllUpdatablePropertiesEquals(CumRap expected, CumRap actual) {
        assertCumRapUpdatableFieldsEquals(expected, actual);
        assertCumRapUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCumRapAutoGeneratedPropertiesEquals(CumRap expected, CumRap actual) {
        assertThat(expected)
            .as("Verify CumRap auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCumRapUpdatableFieldsEquals(CumRap expected, CumRap actual) {
        assertThat(expected)
            .as("Verify CumRap relevant properties")
            .satisfies(e -> assertThat(e.getTenCumRap()).as("check tenCumRap").isEqualTo(actual.getTenCumRap()))
            .satisfies(e -> assertThat(e.getLogo()).as("check logo").isEqualTo(actual.getLogo()))
            .satisfies(e -> assertThat(e.getLogoContentType()).as("check logo contenty type").isEqualTo(actual.getLogoContentType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCumRapUpdatableRelationshipsEquals(CumRap expected, CumRap actual) {}
}
