package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DanhSachBapNuocAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhSachBapNuocAllPropertiesEquals(DanhSachBapNuoc expected, DanhSachBapNuoc actual) {
        assertDanhSachBapNuocAutoGeneratedPropertiesEquals(expected, actual);
        assertDanhSachBapNuocAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhSachBapNuocAllUpdatablePropertiesEquals(DanhSachBapNuoc expected, DanhSachBapNuoc actual) {
        assertDanhSachBapNuocUpdatableFieldsEquals(expected, actual);
        assertDanhSachBapNuocUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhSachBapNuocAutoGeneratedPropertiesEquals(DanhSachBapNuoc expected, DanhSachBapNuoc actual) {
        assertThat(expected)
            .as("Verify DanhSachBapNuoc auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhSachBapNuocUpdatableFieldsEquals(DanhSachBapNuoc expected, DanhSachBapNuoc actual) {
        assertThat(expected)
            .as("Verify DanhSachBapNuoc relevant properties")
            .satisfies(e -> assertThat(e.getSoDienThoai()).as("check soDienThoai").isEqualTo(actual.getSoDienThoai()))
            .satisfies(e -> assertThat(e.getTenBapNuoc()).as("check tenBapNuoc").isEqualTo(actual.getTenBapNuoc()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhSachBapNuocUpdatableRelationshipsEquals(DanhSachBapNuoc expected, DanhSachBapNuoc actual) {
        assertThat(expected)
            .as("Verify DanhSachBapNuoc relationships")
            .satisfies(e -> assertThat(e.getVe()).as("check ve").isEqualTo(actual.getVe()));
    }
}
