package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LoaiGheAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoaiGheAllPropertiesEquals(LoaiGhe expected, LoaiGhe actual) {
        assertLoaiGheAutoGeneratedPropertiesEquals(expected, actual);
        assertLoaiGheAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoaiGheAllUpdatablePropertiesEquals(LoaiGhe expected, LoaiGhe actual) {
        assertLoaiGheUpdatableFieldsEquals(expected, actual);
        assertLoaiGheUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoaiGheAutoGeneratedPropertiesEquals(LoaiGhe expected, LoaiGhe actual) {
        assertThat(expected)
            .as("Verify LoaiGhe auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoaiGheUpdatableFieldsEquals(LoaiGhe expected, LoaiGhe actual) {
        assertThat(expected)
            .as("Verify LoaiGhe relevant properties")
            .satisfies(e -> assertThat(e.getTenLoai()).as("check tenLoai").isEqualTo(actual.getTenLoai()))
            .satisfies(e -> assertThat(e.getGiaTien()).as("check giaTien").isEqualTo(actual.getGiaTien()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoaiGheUpdatableRelationshipsEquals(LoaiGhe expected, LoaiGhe actual) {}
}
