package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PhongAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhongAllPropertiesEquals(Phong expected, Phong actual) {
        assertPhongAutoGeneratedPropertiesEquals(expected, actual);
        assertPhongAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhongAllUpdatablePropertiesEquals(Phong expected, Phong actual) {
        assertPhongUpdatableFieldsEquals(expected, actual);
        assertPhongUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhongAutoGeneratedPropertiesEquals(Phong expected, Phong actual) {
        assertThat(expected)
            .as("Verify Phong auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhongUpdatableFieldsEquals(Phong expected, Phong actual) {
        assertThat(expected)
            .as("Verify Phong relevant properties")
            .satisfies(e -> assertThat(e.getTenPhong()).as("check tenPhong").isEqualTo(actual.getTenPhong()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhongUpdatableRelationshipsEquals(Phong expected, Phong actual) {
        assertThat(expected)
            .as("Verify Phong relationships")
            .satisfies(e -> assertThat(e.getRap()).as("check rap").isEqualTo(actual.getRap()));
    }
}
