package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SuatChieuAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSuatChieuAllPropertiesEquals(SuatChieu expected, SuatChieu actual) {
        assertSuatChieuAutoGeneratedPropertiesEquals(expected, actual);
        assertSuatChieuAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSuatChieuAllUpdatablePropertiesEquals(SuatChieu expected, SuatChieu actual) {
        assertSuatChieuUpdatableFieldsEquals(expected, actual);
        assertSuatChieuUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSuatChieuAutoGeneratedPropertiesEquals(SuatChieu expected, SuatChieu actual) {
        assertThat(expected)
            .as("Verify SuatChieu auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSuatChieuUpdatableFieldsEquals(SuatChieu expected, SuatChieu actual) {
        assertThat(expected)
            .as("Verify SuatChieu relevant properties")
            .satisfies(e -> assertThat(e.getNgayChieu()).as("check ngayChieu").isEqualTo(actual.getNgayChieu()))
            .satisfies(e -> assertThat(e.getGioChieu()).as("check gioChieu").isEqualTo(actual.getGioChieu()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSuatChieuUpdatableRelationshipsEquals(SuatChieu expected, SuatChieu actual) {
        assertThat(expected)
            .as("Verify SuatChieu relationships")
            .satisfies(e -> assertThat(e.getPhong()).as("check phong").isEqualTo(actual.getPhong()))
            .satisfies(e -> assertThat(e.getPhim()).as("check phim").isEqualTo(actual.getPhim()));
    }
}
